### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by maxibanki** [maxibanki/golang-url-shortener#3]
Create Dockerfile

**Comment by untalpierre** [comment]
Hey, really cool project. Do you need multi-arch image or just a specific arch image (e.g. amd64, arm)?

**Comment by maxibanki** [comment]
Hey, nice to hear that you like the project. I think it's okay (in 2017), if we only support amd64. But it would be really smart, if the Dokerfile supports multi arch (maybe also Windows) because Go also supports so much architectures. (Raspberry Pi could be also a possible afaik). I personally do not have so much experience in building Dockerfiles, only using or adjusting them for my needs.

**Comment by untalpierre** [comment]
Ya, I believe amd64 and arm would be a good entry point for docker images (i have 0 knowledge on docker for windows and/or windows containers atm). I'll do some digging on this topic as soon as i have free time from college.

**Comment by maxibanki** [comment]
Glad to hear, that you can take over this issue.
